#!/bin/bash

while true
do
    #main.pyが何個起動しているかカウントする
    count=`ps -ef | grep python botdes/main.py | grep -v grep | wc -l`
    #監視するmain.pyが0個の場合、ダウンしているので起動
    if [ $count = 0 ]; then
        bash botdesu.sh
    fi
    sleep 600 #モニタ間隔（秒単位）
done
